@STUDY.ASP.ShiftLoggerTrySix_HostAddress = http://localhost:5156

GET {{STUDY.ASP.ShiftLoggerTrySix_HostAddress}}/shifts

###

POST {{STUDY.ASP.ShiftLoggerTrySix_HostAddress}}/shifts
Content-Type: application/json

{
  "Id": 1,
  "EmployeeId": 2,
  "ClockIn": "2023-12-30",
  "ClockOut": "2023-01-01",
  "isDoneWorking": false
}

###

