@STUDY.ASP.ShiftLoggerTrySix_HostAddress = http://localhost:5156

GET {{STUDY.ASP.ShiftLoggerTrySix_HostAddress}}/shifts

###

POST {{STUDY.ASP.ShiftLoggerTrySix_HostAddress}}/shifts
Content-Type: application/json

{
  "Id": 1,
  "EmployeeId": 2,
  "ClockIn": "2023-12-30T12:12:12",
  "ClockOut": "2023-12-30T13:13:00",
  "isDoneWorking": false
}

###

