# For more info on HTTP files go to https://aka.ms/vs/httpfile

GET http://localhost:5127/todos

###

POST http://localhost:5127/todos
content-type: application/json

{
  "id": 2,
  "name": "Write demo",
  "dueDate": "2026-12-31",
  "isCompleted": false
}

###

GET http://localhost:5127/todos/2

###

DELETE http://localhost:5127/todos/2

###

GET http://localhost:5127/tasks/1